name: My Second Workflow

#trigger 
on: 
  push:
    branches:    
    - release/[A-Za-z0-9.]+
# Jobs in the workflow
jobs:
  # job name
  my-second-workflow:
    # OS that this workflow will be running on
    runs-on: ubuntu-latest

  # list of steps to perform task
    steps:   
    - name: Checkout the current repo
      uses: actions/checkout@v3
      with:
        ref: " ${{ github.ref }} "
    - name: List my current directory after checkout
      run: ls -l